# Generated by Django 4.0.4 on 2022-05-05 02:59

from django.db import migrations, models
import home.utils


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_Img', models.ImageField(storage=home.utils.MyFileStorage(), upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Element_oo',
        ),
    ]
